 version: 0.0
 os: linux

 files:             
  - source: webapp/target/ROOT.war
    destination: /opt/tomcat/webapps
  - source: cloudwatch-config.json
    destination: /opt

 hooks:
   BeforeInstall: 
    - location: infrastructure/aws/codedeploy/beforeInstall.sh
      timeout: 180
      runas: root
   ApplicationStart:
    - location: infrastructure/aws/codedeploy/applicationstart.sh
      timeout: 180
      runas: root
   ApplicationStop:
    - location: infrastructure/aws/codedeploy/applicationstop.sh
      timeout: 180
      runas: root
   AfterInstall:
    - location: infrastructure/aws/codedeploy/afterInstall.sh
      timeout: 180
      runas: root
