 version: 0.0
 os: linux

 files:             
  - source: ./webapp/target/ROOT.war
    destination: /opt/tomcat/webapps

 hooks:
 ApplicationStop:
    - location: infrastructure/aws/codedeploy/applicationstop.sh
      timeout: 180
      runas: centos
 BeforeInstall: 
    - location: infrastructure/aws/codedeploy/beforeInstall.sh
      timeout: 180
      runas: centos
 AfterInstall:
    - location: infrastructure/aws/codedeploy/afterInstall.sh
      timeout: 180
      runas: centos
 ApplicationStart:
    - location: infrastructure/aws/codedeploy/applicationstart.sh
      timeout: 180
      runas: centos